version: "3.8"

services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"
    environment:
      - SE_GRID_MAX_SESSION=5
      - SE_GRID_MAX_INSTANCES=10

  chrome-node:
    image: selenium/node-chrome
    shm_size: "2g"
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    deploy:
      replicas: 5  # Start with 2 Chrome nodes (scale manually if needed)
      mode: replicated
      resources:
        limits:
          cpus: "1"
          memory: "1g"
        reservations:
          cpus: "0.5"
          memory: "512M"
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 5

  firefox-node:
    image: selenium/node-firefox
    shm_size: "2g"
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    deploy:
      replicas: 1  # Start with 1 Firefox node
      mode: replicated
      resources:
        limits:
          cpus: "1"
          memory: "1g"
        reservations:
          cpus: "0.5"
          memory: "512M"
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1

  edge-node:
    image: selenium/node-edge
    shm_size: "2g"
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    deploy:
      replicas: 1  # Start with 1 Edge node
      mode: replicated
      resources:
        limits:
          cpus: "1"
          memory: "1g"
        reservations:
          cpus: "0.5"
          memory: "512M"
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
