name: Flipkart Automation Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '30 20 * * *'  # Runs at 8:30 PM UTC every day
  workflow_dispatch:

jobs:
  selenium-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '19'
          
      - name: Set up Docker
        run: docker --version  # Just to verify Docker is installed

      - name: Start Selenium Grid with Docker Compose
        run: docker compose up -d

      - name: Wait for Selenium Grid to be Ready
        run: |
          echo "Waiting for Selenium Grid to start..."
          sleep 20

      - name: Run TestNG Tests
        run: mvn test -Dsurefire.suiteXmlFiles=testng.xml

      - name: Stop Selenium Grid
        run: docker compose down
        
      - name: Upload FAS Test Report
        uses: actions/upload-artifact@v4
        with:
          name: Extent-Test-Report
          path: extent-test-output/Index.html
          retention-days: 7
